url: http://filippovitale.it
title: Morning comes too early and nighttime falls too late
subtitle: Reincarnation of my old blog
pygments: true

author :
  name : Filippo Vitale
  github : filippovitale
  twitter : filippovitale

root: /
permalink: /article/:title/
