url: http://filippovitale.it
title: Morning comes too early and nighttime falls too late
subtitle: TODO subtitle
pygments: true

author :
  name : Filippo Vitale
  github : filippovitale
  twitter : filippovitale

root: /
permalink: /:year/:title/
