url: http://filippovitale.it
title: Morning comes too early and nighttime falls too late

highlighter: rouge

author:
  name: Filippo Vitale
  github: filippovitale
  twitter: filippovitale
  slideshare: filippovitale

root: /
permalink: /article/:title/
